[package]
name = "mpu6050_driver"
version = "0.1.0"
authors = ["Callum Mackenzie <alexxander1611@gmail.com>"]
edition = "2018"

[dependencies]
embedded-hal = "0.2.3"
i2c_tools = { path = "../i2c_tools" }
elinalgebra = { path = "../elinalgebra" }
micromath = "2.0.0"